<h1>Broadcasting and vectors


In [1]:
import numpy as np

In [12]:
a = np.arange(4)
a.size

4

In [13]:
a * 10

array([ 0, 10, 20, 30])

In [14]:
l = [0,1,2,3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [15]:
a = np.arange(4)
b = np.array([10,20,30,40])

In [16]:
a + b

array([10, 21, 32, 43])

In [17]:
a * b

array([  0,  20,  60, 120])

<h1>Boolean arrays

In [18]:
a = np.arange(4)

In [23]:

a[[True,True,False,True]]

array([0, 1, 3])

In [24]:
a[[True,False,True,False]]

array([0, 2])

In [25]:
a >= 2

array([False, False,  True,  True])

<h2>Checking if index bigger than mean


In [27]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
a.mean()

3.5

In [30]:
a > a.mean()

array([False, False, False, False,  True,  True,  True,  True])

In [31]:
a[a > a.mean()]

array([4, 5, 6, 7])

In [33]:
a[~(a > a.mean())] # means not

array([0, 1, 2, 3])

In [34]:
A  = np.random.randint(100, size=(3,3))
A

array([[29, 23,  5],
       [77, 44, 38],
       [96, 44,  6]])

In [35]:
A[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([29,  5, 44, 96,  6])

In [36]:
A > 50

array([[False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [37]:
A[A>50]

array([77, 96])