<h1>Importing Ops </h1>

In [ ]:
import numpy as np
import sys

<h2>Basic arrays with numpy

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
a = np.array([1, 2, 3])
b = np.array([0, .5, 1])

In [4]:
a[1], b[1]

(2, 0.5)

In [8]:
#a[0:]
a[::2] # every other element with 2 steps

array([1, 3])

In [14]:
#multi indexes
#[a[1], a[2], a[0]]
a[[2,1,0]]

array([3, 2, 1])

<h1 style="color:green">Reverse an existed list with indexes

In [15]:
c = np.array([1,2,3,4,5,6])

In [16]:
c[::-1]

array([6, 5, 4, 3, 2, 1])

In [17]:
c[[5,4,3,2,1,0]]

array([6, 5, 4, 3, 2, 1])

<h2>NumPy Array types


In [18]:
a = np.array([1, 2, 3,4, 5, 6])
a.dtype

dtype('int32')

In [19]:
np.array([1, 2, 3, 4, 5, 6], dtype=np.float32)

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [20]:
np.array(['a', 'b', 'c']).dtype

dtype('<U1')

<h3>MultiDimensional arrays

In [21]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])


In [22]:
a.shape

(2, 4)

In [23]:
a.ndim

2

In [24]:
a.size

8

<h3 style='color:green;'>Create three dimensional array

In [28]:
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [29]:
c.shape

(3, 3)

In [30]:
c.ndim

2

In [31]:
c.mean()

5.0

<h2>Indexing and slicing of matrices

In [35]:
a[1]

array([4, 5, 6])

In [36]:
a[1][0]

4

In [37]:
a[1,0]

4

In [38]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
#square matrix
a = np.array([
    #0 1 2
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
    ])

In [41]:
a[:1, :3] # birinci yukseklik ikinci genislik

array([[1, 2, 3]])

In [43]:
a[1] = np.array([10, 10, 10])

In [44]:
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [45]:
a[2] = 99

In [46]:
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

<h2> Summary statics

In [56]:
a = np.array([1, 2, 3,1,2,4, 5, 6])

In [48]:
a

array([1, 2, 3, 4, 5, 6])

In [49]:
a.sum()

21

In [57]:
a.mean()

3.0

In [58]:
a.std()

1.7320508075688772

In [59]:
a.var()

3.0

<h1 style='color:green'>Task : get first two elements of each dimension from 3 x 3 to 2 x 2

In [72]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
    
    #[1,2]
    #[4,5]
    

In [63]:
a[:2, :2] # birinci yukseklik ikinci genislik

array([[1, 2],
       [4, 5]])

In [73]:
el1 = a[0,2]
el2 = a[1,0]
a = a[:2, :2]
a[1] = [el1, el2]

In [74]:
a


array([[1, 2],
       [3, 4]])